version: 2.1

python: &python
  image: cimg/python:3.9.13

jobs:
  auto:
    working_directory: ~/greatauto
    docker:
      - <<: *python
    steps:
      - checkout
      - run:
          name: "Auto"
          command: |
            # python3 -m venv the_venv
            # source the_venv/bin/activate
            python3 -m pip install -q -r requirements.txt
            BROWSERSTACK_USERNAME="$BROWSERSTACK_USERNAME" BROWSERSTACK_ACCESS_KEY="$BROWSERSTACK_ACCESS_KEY" browserstack-sdk pytest tests/international/international_contact_test.py::test_contact_invest_success

workflows:
  auto-workflow:
    jobs:
      - auto
